services:
  tg-bot-scheduler:
    build: .
    container_name: tg-bot-scheduler
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Novosibirsk
    restart: unless-stopped
    working_dir: /app/src
    command: ["python3", "-u", "bot.py"]
